import i18n, { currentDateLocale } from '../i18n/index.js';

export const REQUEST_STATUSES = [
  'PENDING',
  'ACCEPTED',
  'IN_PROGRESS',
  'COMPLETED',
  'CANCELLED',
];

export const BOOKING_GROUPS = ['UPCOMING', 'ACTIVE', 'COMPLETED', 'CANCELLED'];

// Status values stay as the API sends them; only their display label is translated.
const STATUS_AUDIENCES = {
  customer: 'request',
  provider: 'provider',
  booking: 'booking',
  externalJob: 'externalJob',
};

export function statusLabel(status, { audience = 'customer' } = {}) {
  const key = `common.status.${STATUS_AUDIENCES[audience] || 'request'}.${status}`;
  return i18n.exists(key) ? i18n.t(key) : status;
}

// The catch-all "OTHER" issue label is generated by the backend (not entered by anyone),
// so it is shown in the UI language; every other issue label is service data, shown as-is.
export function formatIssueLabel(issueKey, issueLabel) {
  return issueKey === 'OTHER' ? i18n.t('common.issueOther') : issueLabel;
}

export function statusTone(status) {
  switch (status) {
    case 'ACCEPTED':
    case 'ASSIGNED':
    case 'SCHEDULED':
      return 'info';
    case 'IN_PROGRESS':
    case 'ON_THE_WAY':
    case 'ARRIVED':
      return 'active';
    case 'COMPLETED':
      return 'success';
    case 'CANCELLED':
      return 'muted';
    default:
      return 'neutral';
  }
}

export function formatCategory(category) {
  if (!category) {
    return '';
  }

  if (category.length <= 3) {
    return category;
  }

  return category.charAt(0) + category.slice(1).toLowerCase();
}

// Backend dates are calendar dates (YYYY-MM-DD), so format them without timezone shifts.
export function formatDate(dateOnly) {
  if (!dateOnly) {
    return '';
  }

  const [year, month, day] = dateOnly.split('-').map(Number);
  return new Date(year, month - 1, day).toLocaleDateString(currentDateLocale(), {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

export function formatTime(time) {
  if (!time) {
    return '';
  }

  const [hours, minutes] = time.split(':').map(Number);
  const date = new Date();
  date.setHours(hours, minutes, 0, 0);
  return date.toLocaleTimeString(currentDateLocale(), { hour: 'numeric', minute: '2-digit' });
}

export function formatSlot(dateOnly, time) {
  return [formatDate(dateOnly), formatTime(time)].filter(Boolean).join(' · ');
}

export function formatTimestamp(value) {
  if (!value) {
    return '';
  }

  return new Date(value).toLocaleDateString(currentDateLocale(), {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

export function formatDateTime(value) {
  if (!value) {
    return '';
  }

  return new Date(value).toLocaleString(currentDateLocale(), {
    day: 'numeric',
    month: 'short',
    hour: 'numeric',
    minute: '2-digit',
  });
}

export function formatClock(value) {
  if (!value) {
    return '';
  }

  return new Date(value).toLocaleTimeString(currentDateLocale(), { hour: 'numeric', minute: '2-digit' });
}

export function formatMoney(amount) {
  if (amount === null || amount === undefined) {
    return '';
  }

  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: Number.isInteger(amount) ? 0 : 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

export function formatRating(rating) {
  return rating === null || rating === undefined ? null : rating.toFixed(1);
}

export function formatAddress(address) {
  if (!address) {
    return '';
  }

  return [address.addressLine, address.city, address.state, address.pincode]
    .filter(Boolean)
    .join(', ');
}

export function firstName(name) {
  return (name || '').trim().split(' ')[0] || i18n.t('common.greeting.fallbackName');
}

export function initials(name) {
  return (name || '')
    .trim()
    .split(/\s+/)
    .slice(0, 2)
    .map((part) => part.charAt(0).toUpperCase())
    .join('');
}

export function todayDateOnly() {
  const now = new Date();
  const offset = now.getTimezoneOffset() * 60000;
  return new Date(now.getTime() - offset).toISOString().slice(0, 10);
}
